import assert from "node:assert/strict";import { cp,mkdir,mkdtemp,readFile,rm,writeFile } from "node:fs/promises";import { tmpdir } from "node:os";import { join } from "node:path";import test from "node:test";import { dedupeFingerprint } from "../scripts/curriculum/certification-planned-slots.mjs";import { artifactFingerprintForPlan,loadAndValidateStage03AI901CandidatePlan,loadStage03AI901CandidatePlan,loadStage03AI901TrustRoot,validateStage03AI901CandidatePlan } from "../scripts/curriculum/certification-stage03-ai901.mjs";import { discoverSourceBatches } from "../scripts/publishing/pipeline.mjs";
const root=process.cwd(),plan=await loadStage03AI901CandidatePlan(root),candidate=mutate=>{const copy=structuredClone(plan);mutate(copy);return validateStage03AI901CandidatePlan(copy,{root})},rehashed=mutate=>{const copy=structuredClone(plan);mutate(copy);copy.artifactFingerprint=artifactFingerprintForPlan(copy);return validateStage03AI901CandidatePlan(copy,{root})};
test("AI901 explicit two-node candidate",async()=>{const r=await loadAndValidateStage03AI901CandidatePlan({root});assert.deepEqual({slots:r.slotCount,targets:r.targetCount,blocks:r.blockCount,sources:r.sourceCount},{slots:258,targets:44,blocks:27,sources:33});assert.deepEqual(r.nodeCounts,{ai_concepts_responsible_models_and_foundry_clients:138,agents_multimodal_and_extraction_implementation:120});assert.equal(r.runtimeReachability.admitted,false)});
test("AI901 fails closed on artifact, semantic, provenance, edge and mode mutation",async()=>{await assert.rejects(candidate(x=>x.slots[35].questionIntent="generic scenario"),/ARTIFACT_FINGERPRINT/);await assert.rejects(rehashed(x=>{const s=x.slots[35];s.questionIntent="generic scenario";s.dedupeFingerprint=dedupeFingerprint(s)}),/SEMANTIC_IDENTITY_MISMATCH/);await assert.rejects(rehashed(x=>{const s=x.slots[35];s.sourceRequirements.directFirstPartyDocumentation[0].testedProperties=["unsupported_property"];s.dedupeFingerprint=dedupeFingerprint(s)}),/DIRECT_SOURCE_BINDING_MISMATCH/);await assert.rejects(rehashed(x=>x.candidateCrossNodeRelationships[0].toBlockId="none"),/EDGE_IDENTITY_MISMATCH/);await assert.rejects(rehashed(x=>x.freePremiumAndModeFeasibility.eligibleModeCounts["certification-exam-simulation"]++),/MODE_FEASIBILITY/)});
test("AI901 anchors and pilot are immutable",async()=>{const pilot=JSON.parse(await readFile("evidence/certification/planned-item-slots/microsoft-azure-ai-fundamentals-ai-901--foundry_prompts_and_model_clients.json","utf8"));assert.deepEqual(plan.slots.slice(0,pilot.slots.length),pilot.slots);const fixture=await mkdtemp(join(tmpdir(),"stage03-ai901-"));try{const file="schemas/curriculum/certification-planned-slot-stage03-ai901-trust-root.json";await mkdir(join(fixture,"schemas/curriculum"),{recursive:true});await cp(file,join(fixture,file));const x=JSON.parse(await readFile(join(fixture,file),"utf8"));x.sourceRecords[0].url="https://example.com";await writeFile(join(fixture,file),JSON.stringify(x));await assert.rejects(loadStage03AI901TrustRoot(fixture),/TRUST_ROOT_DIGEST_MISMATCH/)}finally{await rm(fixture,{recursive:true,force:true})}});
test("AI901 evidence is excluded from runtime source discovery",async()=>{const fixture=await mkdtemp(join(tmpdir(),"stage03-ai901-runtime-"));try{await mkdir(join(fixture,"manual/source/candidate"),{recursive:true});await mkdir(join(fixture,"evidence/certification/planned-item-slot-track-plans"),{recursive:true});await writeFile(join(fixture,"manual/source/candidate/source.json"),"{}");await writeFile(join(fixture,"evidence/certification/planned-item-slot-track-plans/candidate.json"),JSON.stringify(plan));assert.deepEqual((await discoverSourceBatches(fixture,"candidate")).map(x=>x.path),[join(fixture,"manual/source/candidate/source.json")])}finally{await rm(fixture,{recursive:true,force:true})}});
test("AI901 reconciliation negative acceptance matrix",async()=>{
  const first=35, second=36, target=plan.targetPlans.find(t=>t.slotIds.includes(plan.slots[first].slotId)), block=plan.blockPlans.find(b=>b.blockId===target.blockId);
  await assert.rejects(rehashed(x=>{for(const i of [first,second]){const s=x.slots[i];s.questionIntent="Assess generic capability.";s.materialEvidenceOrConstraintChanged=["generic capability"];s.expectedOutcome.resolution="Resolve generic capability.";s.errorModelOrFailureMode="Ignore generic capability evidence.";s.decisiveBoundary="Generic capability governs the generic outcome.";s.transferBoundary="Transfer when generic capability changes.";s.neighborDistinctness=[{neighborSlotId:x.slots[i===first?second:first].slotId,explanation:"This slot changes generic capability and resolves classification; the neighbour changes generic capability and resolves classification."}];s.dedupeFingerprint=dedupeFingerprint(s)}}),/SEMANTIC_IDENTITY_MISMATCH/);
  await rehashed(x=>{const s=x.slots[first];s.questionIntent=s.questionIntent.replace("Diagnose", "Diagnose\u00a0 ");s.dedupeFingerprint=dedupeFingerprint(s)});
  await assert.rejects(rehashed(x=>{for(const id of target.slotIds){x.candidateNodeOwnership[id]="agents_multimodal_and_extraction_implementation";const s=x.slots.find(y=>y.slotId===id);s.nodeId="agents_multimodal_and_extraction_implementation";s.dedupeFingerprint=dedupeFingerprint(s)}x.targetPlans.find(t=>t.coverageTargetId===target.coverageTargetId).candidateNodeId="agents_multimodal_and_extraction_implementation"}),/DERIVED_OWNERSHIP_MISMATCH/);
  await assert.rejects(rehashed(x=>{const t=x.targetPlans.find(t=>t.slotIds.includes(x.slots[first].slotId));t.candidateSlotCount++;t.sourceRefs.push("ms-language-overview")}),/DERIVED_TARGET_PLAN_MISMATCH/);
  await assert.rejects(rehashed(x=>{x.blockPlans.find(b=>b.blockId===block.blockId).sourceRefs=[]}),/DERIVED_BLOCK_PLAN_MISMATCH/);
  await assert.rejects(rehashed(x=>{x.candidateNodes[0].blockIds=[];x.candidateNodes[0].absorbedCurrentNodeIds=[];x.candidateNodes[0].candidateSlotCount=0}),/DERIVED_NODE_PLAN_MISMATCH/);
  await assert.rejects(rehashed(x=>{const s=x.slots[first];s.sourceRequirements.officialObjective.objectiveRefs=[];s.dedupeFingerprint=dedupeFingerprint(s)}),/OFFICIAL_OBJECTIVE_BINDING_MISMATCH/);
  await assert.rejects(rehashed(x=>{const s=x.slots[first];s.sourceRequirements.officialObjective.sourceRefs=["microsoft-ai-901-exam-page"];s.dedupeFingerprint=dedupeFingerprint(s)}),/OFFICIAL_OBJECTIVE_BINDING_MISMATCH/);
  await assert.rejects(rehashed(x=>{const s=x.slots[first];s.sourceRequirements.officialObjective.registryRef="config/other.json";s.dedupeFingerprint=dedupeFingerprint(s)}),/OFFICIAL_OBJECTIVE_BINDING_MISMATCH/);
  await assert.rejects(rehashed(x=>{const s=x.slots[0];s.officialObjectiveRefs=["ai-901-2026-04-15-1.2","ai-901-2026-04-15-2.1"]}),/PILOT_MISMATCH/);
  const language=plan.slots.findIndex(s=>s.slotId.includes("language-detection"));
  await assert.rejects(rehashed(x=>{const s=x.slots[language];s.sourceRequirements.directFirstPartyDocumentation[0].sourceRefs=["ms-language-summarization"];s.dedupeFingerprint=dedupeFingerprint(s);const t=x.targetPlans.find(t=>t.coverageTargetId===s.coverageTargetId);t.sourceRefs=[...new Set(x.slots.filter(y=>y.coverageTargetId===s.coverageTargetId).flatMap(y=>y.sourceRequirements.directFirstPartyDocumentation.flatMap(q=>q.sourceRefs)))].sort()}),/DIRECT_SOURCE_BINDING_MISMATCH/);
  await assert.rejects(rehashed(x=>{const s=x.slots[first];s.sourceRequirements.directFirstPartyDocumentation[0].testedProperties=["another_property"];s.sourceRequirements.directFirstPartyDocumentation[0].sourceRefs=["ms-foundry-overview"];s.dedupeFingerprint=dedupeFingerprint(s);const t=x.targetPlans.find(t=>t.coverageTargetId===s.coverageTargetId);t.sourceRefs=[...new Set(x.slots.filter(y=>y.coverageTargetId===s.coverageTargetId).flatMap(y=>y.sourceRequirements.directFirstPartyDocumentation.flatMap(q=>q.sourceRefs)))].sort()}),/DIRECT_SOURCE_BINDING_MISMATCH/);
  await assert.rejects(rehashed(x=>{const e=x.candidateCrossNodeRelationships[0];e.fromBlockId="system_user_prompt_design";e.fromAtomId="classify_system_user_prompt_design_evidence"}),/EDGE_IDENTITY_MISMATCH/);
  const dual=plan.slots.find(s=>s.slotId.includes("safety_filter_boundary:slot:groundedness-harm-filter-boundary"));
  await assert.rejects(rehashed(x=>{x.simulationDomainOwnership[dual.slotId].domainId="ai-901-2026-04-15-domain-2"}),/DOMAIN_BINDING_MISMATCH/);
});
test("AI901 rejects coordinated duplicated block-plan omission",async()=>{
  await assert.rejects(rehashed(x=>{x.blockPlans[1]=structuredClone(x.blockPlans[0]);for(const n of x.candidateNodes)n.blockIds=x.blockPlans.filter(b=>b.candidateNodeId===n.nodeId).map(b=>b.blockId).sort()}),/DERIVED_BLOCK_PLAN_MISMATCH/);
});
test("AI901 rejects coordinated duplicated edge omission",async()=>{
  await assert.rejects(rehashed(x=>{x.candidateCrossNodeRelationships[1]=structuredClone(x.candidateCrossNodeRelationships[0])}),/EDGE_ROSTER_MISMATCH/);
});
test("AI901 derives exact family mode minima",async()=>{
  await assert.rejects(rehashed(x=>{x.freePremiumAndModeFeasibility.requiredUniqueItems["certification-exam-simulation"]=0}),/MODE_FEASIBILITY/);
  await assert.rejects(rehashed(x=>{delete x.freePremiumAndModeFeasibility.requiredUniqueItems["certification-exam-simulation"]}),/MODE_FEASIBILITY/);
});
test("AI901 binds practice and candidate-node narrative boundaries",async()=>{
  await assert.rejects(rehashed(x=>{x.examSimulationBlueprint.candidatePracticeForm.behaviorBoundary="Provider-faithful simulation with exact scoring and navigation."}),/PRACTICE_BOUNDARY_MISMATCH/);
  await assert.rejects(rehashed(x=>{x.candidateNodes[0].rationale="Provider-faithful exact timing format contract."}),/PRACTICE_BOUNDARY_MISMATCH/);
});
test("AI901 derives the complete official evidence object from Stage01",async()=>{
  await assert.rejects(rehashed(x=>{x.examSimulationBlueprint.officialAI901Evidence.studyGuideVersion={value:"forged",sourceRef:"microsoft-ai-901-exam-page"}}),/OFFICIAL_EVIDENCE_MISMATCH/);
  await assert.rejects(rehashed(x=>{x.examSimulationBlueprint.officialAI901Evidence.domainWeights={values:["99%","1%"],sourceRef:"microsoft-ai-901-exam-page"}}),/OFFICIAL_EVIDENCE_MISMATCH/);
  await assert.rejects(rehashed(x=>{x.examSimulationBlueprint.officialAI901Evidence.sectionTopology={status:"documented",value:"forged"}}),/OFFICIAL_EVIDENCE_MISMATCH/);
});
test("AI901 closes remaining declaration surface",async()=>{
  await assert.rejects(rehashed(x=>{x.status="runtime-ready authoring-complete"}),/DECLARATION_SURFACE_MISMATCH/);
  await assert.rejects(rehashed(x=>{x.humanEditorialApproval="approved by a human editor"}),/DECLARATION_SURFACE_MISMATCH/);
  await assert.rejects(rehashed(x=>{x.questions=["learner-facing content"]}),/DECLARATION_SURFACE_MISMATCH/);
  await assert.rejects(rehashed(x=>{x.targetPlans[0].questions=["nested learner-facing content"]}),/LEARNER_FIELD/);
  await assert.rejects(rehashed(x=>{x.scope.runtimeRoute="published"}),/DECLARATION_SURFACE_MISMATCH/);
  await assert.rejects(rehashed(x=>{x.repositoryBaseline.currentAggregateTargetItemCount=1}),/DECLARATION_SURFACE_MISMATCH/);
  await assert.rejects(rehashed(x=>{x.derivedCounts.sourceCount=0}),/DERIVED_COUNT_DRIFT/);
  await assert.rejects(rehashed(x=>{x.canonicalPreservation.pilotSlotArrayCanonicalJsonSha256="0".repeat(64)}),/PILOT_MISMATCH/);
  await assert.rejects(rehashed(x=>{x.boundaryRelationshipRemap={x:"y"}}),/CANONICAL_MUTATION/);
  await assert.rejects(rehashed(x=>{x.pilotTransferBoundaries[Object.keys(x.pilotTransferBoundaries)[0]]="different meaningful external transfer boundary."}),/PILOT_TRANSFER/);
  await assert.rejects(rehashed(x=>{x.freePremiumAndModeFeasibility.packageBoundary="runtime-ready provider-faithful package"}),/DECLARATION_SURFACE_MISMATCH/);
  await assert.rejects(rehashed(x=>{x.freePremiumAndModeFeasibility.packageBoundary="Free and Premium packages use a different learner-access split."}),/PRACTICE_BOUNDARY_MISMATCH/);
});
