import assert from "node:assert/strict";
import { cp,mkdir,mkdtemp,readFile,rm,writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { dedupeFingerprint } from "../scripts/curriculum/certification-planned-slots.mjs";
import { artifactFingerprintForPlan,loadAndValidateStage03KCNACandidatePlan,loadStage03KCNACandidatePlan,loadStage03KCNATrustRoot,validateStage03KCNACandidatePlan } from "../scripts/curriculum/certification-stage03-kcna.mjs";
import { discoverSourceBatches } from "../scripts/publishing/pipeline.mjs";

const root=process.cwd(),plan=await loadStage03KCNACandidatePlan(root),rehashed=mutate=>{const x=structuredClone(plan);mutate(x);x.artifactFingerprint=artifactFingerprintForPlan(x);return validateStage03KCNACandidatePlan(x,{root})};
test("KCNA materializes the reconciled two-node bottom-up contract",async()=>{const r=await loadAndValidateStage03KCNACandidatePlan({root});assert.deepEqual({slots:r.slotCount,targets:r.targetCount,blocks:r.blockCount,sources:r.sourceCount},{slots:257,targets:46,blocks:31,sources:62});assert.deepEqual(r.nodeCounts,{cloud_native_kubernetes_and_service_operating_foundations:128,cloud_native_state_security_delivery_and_reliability:129});assert.deepEqual(plan.reconciliation,{reconciliationFingerprint:"06aa8af8f2bc0bde29a895df4b4ecc7d350cf3503abd9aacb372fe0d4ef0ba4b",sourcePlanFingerprint:"d6eded078207ca6cb2f89b2df3432869749567c5d61fd6322a80cd28d8b3a49a",reviewedSlotCount:319,retainedSlotCount:257,deletedOrMergedSlotCount:62});assert.equal(r.runtimeReachability.admitted,false)});
test("KCNA trust root is byte-digested",async()=>{const fixture=await mkdtemp(join(tmpdir(),"stage03-kcna-"));try{const file="schemas/curriculum/certification-planned-slot-stage03-kcna-trust-root.json";await mkdir(join(fixture,"schemas/curriculum"),{recursive:true});await cp(file,join(fixture,file));const x=JSON.parse(await readFile(join(fixture,file),"utf8"));x.sourceRecords[0].url="https://example.com";await writeFile(join(fixture,file),JSON.stringify(x));await assert.rejects(loadStage03KCNATrustRoot(fixture),/TRUST_ROOT_DIGEST_MISMATCH/)}finally{await rm(fixture,{recursive:true,force:true})}});
test("KCNA fails closed on coordinated semantic and direct-source co-mutation",async()=>{await assert.rejects(rehashed(x=>{for(const i of [0,1]){const s=x.slots[i];s.questionIntent="generic scenario";s.materialEvidenceOrConstraintChanged=["generic fact"];s.expectedOutcome.resolution="generic outcome";s.decisiveBoundary="generic boundary";s.errorModelOrFailureMode="generic failure";s.transferBoundary="generic transfer boundary";s.dedupeFingerprint=dedupeFingerprint(s)}}),/SEMANTIC_OR_SOURCE_IDENTITY_MISMATCH/);await assert.rejects(rehashed(x=>{const s=x.slots[0];s.sourceRequirements.directFirstPartyDocumentation[0].sourceRefs=["k8s-components"];s.dedupeFingerprint=dedupeFingerprint(s)}),/SEMANTIC_OR_SOURCE_IDENTITY_MISMATCH/)});
test("KCNA rejects coordinated roster omission and package/mode weakening",async()=>{await assert.rejects(rehashed(x=>{x.targetPlans[1]=structuredClone(x.targetPlans[0])}),/TARGET_ROSTER_MISMATCH/);await assert.rejects(rehashed(x=>{x.blockPlans[1]=structuredClone(x.blockPlans[0])}),/(DERIVED_OWNERSHIP|BLOCK_ROSTER)_MISMATCH/);await assert.rejects(rehashed(x=>{x.candidateCrossNodeRelationships[1]=structuredClone(x.candidateCrossNodeRelationships[0])}),/EDGE_IDENTITY_MISMATCH/);await assert.rejects(rehashed(x=>{x.freePremiumAndModeFeasibility.requiredUniqueItems["certification-exam-simulation"]=0}),/MODE_FEASIBILITY/)});
test("KCNA rejects ownership, fake pilot and blueprint/evidence forgery",async()=>{await assert.rejects(rehashed(x=>{x.canonicalPreservation.pilotSlotCount=1}),/CANONICAL_MUTATION/);await assert.rejects(rehashed(x=>{x.boundaryRelationshipRemap={old:"new"}}),/CANONICAL_MUTATION/);await assert.rejects(rehashed(x=>{x.examSimulationBlueprint.officialKCNAEvidence.itemCount.value=1}),/INVALID_BLUEPRINT/);await assert.rejects(rehashed(x=>{x.examSimulationBlueprint.candidatePracticeForm.domainAllocation[0].itemCount=60}),/INVALID_BLUEPRINT/);await assert.rejects(rehashed(x=>{const s=x.slots[0];x.candidateNodeOwnership[s.slotId]="cloud_native_state_security_delivery_and_reliability";s.nodeId="cloud_native_state_security_delivery_and_reliability";s.dedupeFingerprint=dedupeFingerprint(s)}),/DERIVED_OWNERSHIP_MISMATCH/)});
test("KCNA excludes planning evidence from runtime source discovery",async()=>{const fixture=await mkdtemp(join(tmpdir(),"stage03-kcna-runtime-"));try{await mkdir(join(fixture,"manual/source/candidate"),{recursive:true});await mkdir(join(fixture,"evidence/certification/planned-item-slot-track-plans"),{recursive:true});await writeFile(join(fixture,"manual/source/candidate/source.json"),"{}");await writeFile(join(fixture,"evidence/certification/planned-item-slot-track-plans/candidate.json"),JSON.stringify(plan));assert.deepEqual((await discoverSourceBatches(fixture,"candidate")).map(x=>x.path),[join(fixture,"manual/source/candidate/source.json")])}finally{await rm(fixture,{recursive:true,force:true})}});
test("KCNA closes every slot and nested declaration surface",async()=>{await assert.rejects(rehashed(x=>{x.questions=["forbidden"]}),/DECLARATION_SURFACE_MISMATCH/);for(const key of ["learnerFacingQuestion","editorialApproval","runtimeState","answerChoices","userPrompt"]){await assert.rejects(rehashed(x=>{x.slots[0][key]="forbidden";x.slots[0].dedupeFingerprint=dedupeFingerprint(x.slots[0])}),/SLOT_DECLARATION_SURFACE/)}await assert.rejects(rehashed(x=>{x.slots[0].expectedOutcome.userPrompt="forbidden";x.slots[0].dedupeFingerprint=dedupeFingerprint(x.slots[0])}),/SLOT_DECLARATION_SURFACE/);await assert.rejects(rehashed(x=>{x.slots[0].sourceRequirements.officialObjective.editorialApproval="forbidden";x.slots[0].dedupeFingerprint=dedupeFingerprint(x.slots[0])}),/SLOT_DECLARATION_SURFACE/);await assert.rejects(rehashed(x=>{x.slots[0].sourceRequirements.directFirstPartyDocumentation[0].answerChoices=[];x.slots[0].dedupeFingerprint=dedupeFingerprint(x.slots[0])}),/SLOT_DECLARATION_SURFACE/);await assert.rejects(rehashed(x=>{x.slots[0].neighborDistinctness=[{neighborSlotId:x.slots[1].slotId,explanation:"A and B are real alternatives owned by the same target, but they resolve different evidence and outcomes under one generic scenario."}];x.slots[0].dedupeFingerprint=dedupeFingerprint(x.slots[0])}),/INVALID_NEIGHBOR_SEMANTICS/);await assert.rejects(rehashed(x=>{x.sourceRecords[0].url="https://kubernetes.io/docs/forged"}),/SOURCE_ANCHOR_MISMATCH/)});
test("KCNA reconciliation rejects forced optional and artificial-neighbor patterns",()=>{const histogram=Object.fromEntries(["errorModelOrFailureMode","decisiveBoundary","transferBoundary"].map(k=>[k,{nonnull:plan.slots.filter(s=>s[k]!==null).length,null:plan.slots.filter(s=>s[k]===null).length}]));assert.deepEqual(histogram,{errorModelOrFailureMode:{nonnull:112,null:145},decisiveBoundary:{nonnull:154,null:103},transferBoundary:{nonnull:42,null:215}});assert.deepEqual({nonempty:plan.slots.filter(s=>s.neighborDistinctness.length).length,empty:plan.slots.filter(s=>!s.neighborDistinctness.length).length},{nonempty:0,empty:257});assert.equal(plan.slots.flatMap(s=>s.neighborDistinctness).length,0);assert.deepEqual(plan.derivedCounts.targetSlotHistogram,{3:2,4:2,5:16,6:19,7:7});assert.equal(plan.slots.some(s=>/Transfer away from this slot if|This slot is decisive only/i.test(JSON.stringify(s))),false)});
