import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { buildTrack, PublishingFailure, publishRelease, validateTrack, verifyArtifact } from "../scripts/publishing/pipeline.mjs";
import { algorithmsBatch, certificationBatch, fixtureRoot } from "./fixtures/manualPublishingFixture.mjs";

async function root(input = {}) { const path = await mkdtemp(join(tmpdir(), "patternly-publishing-")); await fixtureRoot(path, input); return path; }
const fails = (code) => (error) => error instanceof PublishingFailure && error.code === code;
test("deterministic discovery and artifact bytes ignore filesystem creation order", async () => { const first = await root({ algorithms: algorithmsBatch() }); const second = await root({ algorithms: algorithmsBatch() }); try { const a = await buildTrack({ root: first, trackId: "algorithms", outputRoot: join(first, "out"), sourceRepositoryCommit: "a".repeat(40) }); const b = await buildTrack({ root: second, trackId: "algorithms", outputRoot: join(second, "out"), sourceRepositoryCommit: "a".repeat(40) }); assert.equal(JSON.stringify(a.artifact), JSON.stringify(b.artifact)); } finally { await rm(first, { recursive: true }); await rm(second, { recursive: true }); } });
test("legacy banks are never a source fallback and empty ingress fails explicitly", async () => { const path = await root({ legacy: true }); try { await assert.rejects(() => validateTrack({ root: path, trackId: "algorithms" }), fails("EMPTY_INGRESS")); } finally { await rm(path, { recursive: true }); } });
test("builder never modifies manual source, never creates approvals, and reports only structural identities", async () => { const path = await root({ algorithms: algorithmsBatch() }); try { const source = join(path, "manual/source/algorithms/fixture.json"); const before = await readFile(source, "utf8"); const built = await buildTrack({ root: path, trackId: "algorithms", outputRoot: join(path, "out"), sourceRepositoryCommit: "b".repeat(40) }); assert.equal(await readFile(source, "utf8"), before); const report = await readFile(built.reportPath, "utf8"); assert.doesNotMatch(report, /prompt|options|feedbackModel|fixture reason/); const missing = await root({ algorithms: algorithmsBatch(), approvals: false }); await assert.rejects(() => validateTrack({ root: missing, trackId: "algorithms" }), fails("MISSING_APPROVAL")); await rm(missing, { recursive: true }); } finally { await rm(path, { recursive: true }); } });
test("invalid source blocks the whole track instead of publishing a subset", async () => { const path = await root({ algorithms: algorithmsBatch({ invalid: true }) }); try { await assert.rejects(() => buildTrack({ root: path, trackId: "algorithms", outputRoot: join(path, "out") }), fails("INVALID_ENVELOPE")); } finally { await rm(path, { recursive: true }); } });
test("pool, IDs, and taxonomy references fail without a corrective path", async () => { for (const [input, code] of [[{ count: 39 }, "INSUFFICIENT_POOL"], [{ duplicate: true }, "DUPLICATE_ID"], [{ badReference: true }, "INVALID_REFERENCE"]]) { const path = await root({ algorithms: algorithmsBatch(input) }); try { await assert.rejects(() => validateTrack({ root: path, trackId: "algorithms" }), fails(code)); } finally { await rm(path, { recursive: true }); } } });
test("immutable artifacts verify byte checksum and releases keep tracks independent", async () => { const path = await root({ algorithms: algorithmsBatch(), certification: certificationBatch() }); try { const out = join(path, "out"); const algorithms = await buildTrack({ root: path, trackId: "algorithms", outputRoot: out, sourceRepositoryCommit: "c".repeat(40) }); assert.equal(algorithms.artifact.fixedPools["algorithms-interview-simulation"].length, 40); await assert.rejects(() => buildTrack({ root: path, trackId: "algorithms", outputRoot: out, sourceRepositoryCommit: "c".repeat(40) }), fails("IMMUTABLE_VERSION")); assert.equal((await verifyArtifact(algorithms.path)).trackId, "algorithms"); const release = await publishRelease({ root: path, releaseId: "algorithms-only", artifactPaths: [algorithms.path], outputRoot: out, sourceRepositoryCommit: "c".repeat(40) }); assert.deepEqual(release.release.artifacts.map((artifact) => artifact.trackId), ["algorithms"]); assert.deepEqual(Object.keys(release.release.artifacts[0]).sort(), ["approvalCoverage", "artifactBytes", "checksumSha256", "contentVersion", "declaredModes", "familyId", "schemaVersion", "sourceRepositoryCommit", "taxonomyVersion", "trackId"]); assert.deepEqual(Object.keys(JSON.parse(release.release.artifacts[0].artifactBytes)).sort(), ["bank", "contentVersion", "envelopeVersion", "schemaVersion", "taxonomyVersion"]); const algorithmBytes = algorithms.artifact.artifactBytes; const certification = await buildTrack({ root: path, trackId: "cloud-certification", outputRoot: out, sourceRepositoryCommit: "c".repeat(40) }); const later = await publishRelease({ root: path, releaseId: "algorithms-and-certification", artifactPaths: [algorithms.path, certification.path], outputRoot: out, sourceRepositoryCommit: "c".repeat(40) }); assert.equal(algorithms.artifact.artifactBytes, algorithmBytes); assert.deepEqual(later.release.artifacts.map((artifact) => artifact.trackId), ["algorithms", "cloud-certification"]); await assert.rejects(() => publishRelease({ root: path, releaseId: "algorithms-only", artifactPaths: [algorithms.path], outputRoot: out, sourceRepositoryCommit: "c".repeat(40) }), fails("IMMUTABLE_VERSION")); } finally { await rm(path, { recursive: true }); } });
test("artifact verification reports a deterministic checksum mismatch", async () => { const path = await root({ algorithms: algorithmsBatch() }); try { const built = await buildTrack({ root: path, trackId: "algorithms", outputRoot: join(path, "out"), sourceRepositoryCommit: "d".repeat(40) }); const raw = JSON.parse(await readFile(built.path, "utf8")); raw.artifactBytes = `${raw.artifactBytes} `; await (await import("node:fs/promises")).writeFile(built.path, JSON.stringify(raw)); await assert.rejects(() => verifyArtifact(built.path), fails("CHECKSUM_MISMATCH")); } finally { await rm(path, { recursive: true }); } });
test("Algorithms builds independently when Certification manual ingress is absent", async () => { const path = await root({ algorithms: algorithmsBatch() }); try { const built = await buildTrack({ root: path, trackId: "algorithms", outputRoot: join(path, "out"), sourceRepositoryCommit: "e".repeat(40) }); assert.equal(built.artifact.trackId, "algorithms"); } finally { await rm(path, { recursive: true }); } });
test("fixtures are outside production ingress and production manual roots contain no generated questions", async () => { const source = await readFile("scripts/publishing/pipeline.mjs", "utf8"); assert.doesNotMatch(source, /tests\/fixtures|tracks\/algorithms|tracks\/cloud-certification/); assert.doesNotMatch(source, /generateQuestion|seed|sample|fallback/); });
